ratings:
    paths:
        - "**"
exclude_paths:
    - "**.rst"
engines:
    fixme:
        enabled: true
    duplication:
        enabled: true
        config:
            languages:
                - python
                - javascript
    radon:
        enabled: true
        config:
            threshold: "C"
    pep8:
        enabled: true
    csslint:
        enabled: true
    eslint:
        enabled: true
