ratings:
    paths:
        - "**"
exclude_paths:
    - ".pylintrc"
    - "intranet/static/vendor/**"
    - "intranet/static/js/vendor/**"
engines:
    fixme:
        enabled: true
    duplication:
        enabled: true
        config:
            languages:
                - python
                - javascript
    radon:
        enabled: true
        config:
            threshold: "C"
    pep8:
        enabled: true
    csslint:
        enabled: true
    eslint:
        enabled: true
